### ISSUE TITLE
Does this support radio buttons? 

### ISSUE THREAD

**Issue by hisham** [tiberiuzuld/angular-auto-save-form#3]
Something like: 

```
<div>
    <input type="radio" ng-model="lunch" value="chicken" name="lunch">
    <input type="radio" ng-model="lunch" value="beef" name="lunch">
    <input type="radio" ng-model="lunch" value="fish" name="lunch">  
</div>
```

Doesn't look it. It seems to require name to be unique for each input.

**Comment by tiberiuzuld** [comment]
Didn't tried that.
I will make it work this week.

**Comment by hisham** [comment]
thanks!

**Comment by tiberiuzuld** [comment]
Hello,

So just only today had time to fix the issue with radio buttons. The only way to fix it was to add a new directive called [auto-save-form-property]. 

For radio inputs or if you want to group inputs on the same property use the [auto-save-form-property] attribute on one the inputs and prefix the name with a group name

``` html
  <ng-form name="myForm" auto-save-form="callback"> 
    <input type="radio" ng-model="user.gender" name="inputGroupName.gender1" 
      auto-save-form-property="inputGroupName.gender" value="male"/>Male
    <input type="radio" ng-model="user.gender" name="inputGroupName.gender2" value="female"/>Female
  </ng-form>
```

Note the [name] needs to be different on each input so the $dirty check will work.
Let me know if you have any more issues, and thank you for your feedback.

Thanks,
Tiberiu
