### ISSUE TITLE
Minor change in README.md

### ISSUE THREAD

**Issue by gvsrini** [tiberiuzuld/angular-auto-save-form#8]
Please change
`<script src="bower_components/angular-auto-save-form/auto-save-form.js"></script>`
to
`<script src="bower_components/angular-auto-save-form/dist/auto-save-form.js"></script>`

Also, please add **underscore** as a dependency.

Great job indeed!

**Comment by tiberiuzuld** [comment]
Hi @gvsrini 
Thanks for the hint in readme.md, made the update.
Lodash is already a dependency.
